### PR TITLE
Trying to commit using alternative method; 

### PR DESCRIPTION
**Pull request by Simplify-IT-Prog**

### CODE REVIEW

**Comment by Simplify-IT-Prog** [comment]
Retry

**Review by MamboMaya — APPROVED** [review]
Adding the remaining files and portions of our project.

**Comment by MamboMaya** [comment]
👍

**Review by MamboMaya — APPROVED** [review]
LGTM 👍  work please!!

**Review by matthiasak — APPROVED** [review]
+1

**Comment by MamboMaya** [comment]
👍

**Pull request merged**
